//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookABike
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike
    {
        public int Bike_Number { get; set; }
        public Nullable<int> Station_Number { get; set; }
        public string Bike_Tipe { get; set; }
        public string Bike_Color { get; set; }
        public Nullable<decimal> Bike_Cost { get; set; }
    }
}
