//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookABike
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike_Time_Hired
    {
        public int Bike_Number { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<System.TimeSpan> Time_Hired { get; set; }
        public Nullable<System.TimeSpan> Time_Returned { get; set; }
    }
}
