//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookABike
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Student
    {
        public int Client_ID { get; set; }
        public Nullable<int> Client_StudentNumber { get; set; }
    }
}
