//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookABike
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Staff_ID { get; set; }
        public Nullable<int> Station_Number { get; set; }
        public string Staff_FirstName { get; set; }
        public string Staff_LastName { get; set; }
        public Nullable<int> Weekly_Salary { get; set; }
        public string Staff_Emial { get; set; }
        public Nullable<int> Staff_ContactNumber { get; set; }
    }
}
